# -*- coding: utf-8 -*-
"""image processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10VqXtgV4CY1Gc6WNe7a1apInihxBNvSW
"""



import os
import cv2
from google.colab.patches import cv2_imshow
img = cv2.imread("/Passport_Photograph.jpg")
img= cv2.resize(img, (200,300))
print(img.shape)
crop = img[80:100,70:130]
cv2_imshow(crop)
cv2.imwrite("//tmp//cropped images//my.jpg",crop)
img_new= cv2.rectangle(img,pt1=(60,70),pt2=(140,100),color =(0, 255, 0),thickness= -1,lineType=16)
cv2_imshow(img)



import os
import cv2
from google.colab.patches import cv2_imshow
img = cv2.imread("/itachi jpg.jpg")
img= cv2.resize(img, (200,300))
print(img.shape)
crop = img[80:100,70:130]
cv2_imshow(crop)
cv2.imwrite("//tmp//cropped images//itachi.jpg",crop)
img_new= cv2.rectangle(img,pt1=(60,70),pt2=(140,100),color =(0, 255, 0),thickness= -1,lineType=16)
cv2_imshow(img)

import os
import cv2
from google.colab.patches import cv2_imshow
img = cv2.imread("/desktop-wallpaper-roronoa-zoro-for-iphone-x-8-7-6.jpg")
img= cv2.resize(img, (200,300))
print(img.shape)
crop = img[30:50,70:130]
cv2_imshow(crop)
cv2.imwrite("//tmp//cropped images//zoro.jpg",crop)
img_new= cv2.rectangle(img,pt1=(70,50),pt2=(120,30),color =(0, 255, 0),thickness= -1,lineType=16)
cv2_imshow(img)

import os
import cv2
from google.colab.patches import cv2_imshow
img = cv2.imread("/naruto.jpg")
img= cv2.resize(img, (200,300))
print(img.shape)
crop = img[80:100,70:130]
cv2_imshow(crop)
cv2.imwrite("//tmp//cropped images//naruto.jpg",crop)
img_new= cv2.rectangle(img,pt1=(60,70),pt2=(140,100),color =(0, 255, 0),thickness= -1,lineType=16)
cv2_imshow(img)

import os
import cv2
from google.colab.patches import cv2_imshow
img = cv2.imread("/content/Monkey-D.webp")
img= cv2.resize(img, (200,300))
print(img.shape)
crop = img[100:130,80:130]
cv2_imshow(crop)
cv2.imwrite("/content/cropped images//Luffy.jpg",crop)
img_new= cv2.rectangle(img,pt1=(60,80),pt2=(130,120),color =(0, 255, 0),thickness= -1,lineType=16)
cv2_imshow(img)

from google.colab import drive
drive.mount('/content/drive')

"""# New Section"""